;
; DesignAssignment_1A.asm
;
; Created: 9/12/2019 10:38:53 PM
; Author : Brysen Kokubun 
;

	.ORG 0X0000
	
	START:
	;---------------LOADING REGISTERS-----------------------------------------;
		LDI R25, 0X10			;LOADS IMMEDIATELY THE VALUE OF 16 INTO THE
								;MULTIPLICAND'S UPPER PORTION OF 16 BITS
		LDI R24, 0X01			;LOADS IMMEDIATELY THE VALUE OF 1 INTO THE 
								;MULTIPLICAND'S LOWER PORTION OF 16 BITS
								;MULTIPLICAND = 4097
							
		LDI R23, 0X01			;LOADS IMMEDIATELY THE VALUE OF 1 INTO THE 
								;MULTIPLIER'S UPPER PORTION OF 16 BITS
		LDI R22, 0X01			;LOADS IMMEDIATELY THE VALUE OF 1 INTO THE 
								;MULTIPLIER'S LOWER PORTION OF 16 BITS
								;MULTIPLIER   = 257
							
		LDI R20, 0X00			;INITIALIZE RESULT REGISTER R20 TO 0
		LDI R19, 0X00			;INITIALIZE RESULT REGISTER R19 TO 0
		LDI R18, 0X00 			;INITIALIZE RESULT REGISTER R18 TO 0
		LDI R17, 0X00			;INITIALIZE RESULT REGISTER R17 TO 0
		LDI R26, 0x00			;INITIALIZE REGISTER FOR NECESSARY CARRY 
		LDI R27, 0X00			;INITIALIZE REGISTER FOR NECESSARY CARRY 
	 
	
		CPI R22, 0				;COMPARES IF LOW HALF OF MULTIPLIER == 0
		BREQ CHECK_REG			;BRANCH TO CHECK_REG IF R22 == 0
	
	START_MULTI:
		INC R22;				;INCREMENT THE VALUE OF LOW HALF OF MULTIPLIER
	
	;---------------MULTIPLICATION BRANCH-------------------------------------;
		MULTI_LOWER:
			ADD R17, R24		;ADDS LOWER 8 BITS OF MULTIPLICAND, 
								;STORES IN R17
			ADC R18, R25		;ADDS UPPER 8 BITS OF MULTIPLICAND, 
								;STORES IN R18, CARRY IF NECESSARY
			ADC R19, R26		;ADDS REGISTER INCASE THERE IS A CARRY 
			ADC R20, R27		;ADDS REGISTER INCASE THERE IS A CARRY 

			DEC R22				;DECREMENTS THE VALUE OF LOW HALF OF MULTIPLIER 
			BRNE MULTI_LOWER    ;IF LOW HALF OF MULTIPLIER IS != 0 THEN BRANCH 
								;TO MULTI_LOWER ELSE CONTINUE
			COM R23;			;COMPLIMENT VALUE IN UPPER HALF OF MULTIPLIER
			INC R23;			;INCREMENT VALUE IN UPPER HALF OF MULTIPLIER

		MULTI_UPPER:
			ADD R17, R24		;ADDS LOWER 8 BITS OF MULTIPLICAND, 
								;STORES IN R17
			ADC R18, R25		;ADDS UPPER 8 BITS OF MULTIPLICAND, 
								;STORES IN R18, CARRY IF NECESSARY
			ADC R19, R26		;ADDS REGISTER INCASE THERE IS A CARRY 
			ADC R20, R27		;ADDS REGISTER INCASE THERE IS A CARRY
			
			DEC R23				;DECREMENT THE VALUE OF UPPER HALF OF MULTIPLIER
			BRNE MULTI_UPPER	;IF UPPER HALF OF MULTIPLIER != 0 THEN BRANCH 
								;TO MULTI_UPPER, ELSE CONTINUE
	
	DONE: JMP DONE				;END OF PROGRAM
	
	Check_Reg:
		CPI R23, 0				;COMPARES IF UPPER HALF OF MULTIPLIER == 0
		BREQ DONE				;BRANCH TO DONE IF R23 == 0 ELSE CONTINUE
		JMP START_MULTI			;JUMP TO START_MULTI LABEL
			

		
	
	
